image: node:latest

cache:
  paths:
    - node_modules/


stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public/

pages:
  stage: deploy
  script:
    - echo "Publish pages"
  artifacts:
    paths:
      - public/
  only:
    - master
